# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ywRBV52OS4QkKdWuNO9pnVauOmmvYKdH
"""

# =============================================================================
#  🇮🇳  3-YEAR INDIAN EQUITY PORTFOLIO DASHBOARD — MULTI-SCENARIO MODEL
#  Wall-Street-grade interactive dashboard for Google Colab
#  Live feeds (yfinance) + offline fallback + Plotly + ipywidgets
# =============================================================================

# -----------------------------------------------------------------------------
# 0. SILENT LIBRARY INSTALL (Colab)
# -----------------------------------------------------------------------------
import subprocess, sys
subprocess.run(
    [sys.executable, "-m", "pip", "install", "-q",
     "yfinance", "plotly", "ipywidgets", "pandas", "numpy", "--upgrade"],
    stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL
)

import warnings
warnings.filterwarnings("ignore")

import yfinance as yf
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import ipywidgets as widgets
from IPython.display import display, HTML, clear_output
from datetime import datetime, timedelta

try:
    from google.colab import output
    output.enable_custom_widget_manager()
except Exception:
    pass

# -----------------------------------------------------------------------------
# 1. CORE CONSTANTS
# -----------------------------------------------------------------------------
TOTAL_CAPITAL   = 1_00_00_000     # ₹1 Crore
BROKERAGE_RATE  = 0.0025          # 0.25% on total volume (invested + current)
STCG_RATE       = 0.20            # 20% on net positive gains after brokerage
BENCHMARK       = "^NSEI"
HOLDING_YEARS   = 3


def inr(x):
    """Format a number in Indian currency style: ₹#,##,###.##"""
    try:
        x = float(x)
    except Exception:
        return "₹0.00"
    if pd.isna(x):
        return "-"
    neg = x < 0
    x = abs(x)
    s = f"{x:,.2f}"
    int_part, dec_part = s.split(".")
    int_part = int_part.replace(",", "")
    if len(int_part) <= 3:
        grouped = int_part
    else:
        last3, rest = int_part[-3:], int_part[:-3]
        parts = []
        while len(rest) > 2:
            parts.insert(0, rest[-2:])
            rest = rest[:-2]
        if rest:
            parts.insert(0, rest)
        grouped = ",".join(parts) + "," + last3
    out = f"₹{grouped}.{dec_part}"
    return f"-{out}" if neg else out


# -----------------------------------------------------------------------------
# 2. ASSET UNIVERSE, SECTORS, THESES
# -----------------------------------------------------------------------------
ASSET_META = {
    "10Y_GSEC": {"name": "10Y Indian G-Sec", "class": "Debt",
                 "sector": "Sovereign Debt", "yield": 0.07,
                 "thesis": "Risk-free sovereign anchor providing fixed 7% p.a. accrual, uncorrelated with equity drawdowns."},
    "AAA_BOND": {"name": "AAA Corporate Bond / Debenture", "class": "Debt",
                 "sector": "Corporate Debt", "yield": 0.08,
                 "thesis": "High-grade corporate debenture offering a modest credit-spread pick-up of 100bps over the G-Sec."},
    "GOLDBEES.NS": {"name": "Nippon India ETF Gold BeES", "class": "Gold",
                     "sector": "Commodity", "yield": 0.09,
                     "thesis": "Sovereign-backed gold ETF used as an inflation hedge and portfolio diversifier against equity/currency shocks."},

    "MARUTI.NS":     {"name": "Maruti Suzuki India Ltd", "class": "Equity", "sector": "Automobiles",
                       "thesis": "India's largest passenger-vehicle maker; a defensive, low-beta compounder riding rural demand recovery and SUV mix upgrades."},
    "BAJAJ-AUTO.NS": {"name": "Bajaj Auto Ltd", "class": "Equity", "sector": "Automobiles",
                       "thesis": "Two/three-wheeler leader with a strong export franchise and EV optionality via Chetak; quality-growth compounder with high payout."},
    "HAL.NS":        {"name": "Hindustan Aeronautics Ltd", "class": "Equity", "sector": "Defense / Capital Goods",
                       "thesis": "Near-monopoly domestic defense-aircraft manufacturer benefiting from indigenization push and a record order backlog; high-beta momentum name."},
    "SIEMENS.NS":    {"name": "Siemens Ltd", "class": "Equity", "sector": "Capital Goods",
                       "thesis": "Diversified industrial automation and electrification major positioned on India's capex and power-infrastructure upcycle."},
    "POLYCAB.NS":    {"name": "Polycab India Ltd", "class": "Equity", "sector": "Capital Goods / Manufacturing",
                       "thesis": "Market-leading cables & wires manufacturer; steady compounder with an expanding FMEG (fans, appliances) distribution business."},
    "AXISBANK.NS":   {"name": "Axis Bank Ltd", "class": "Equity", "sector": "Financials",
                       "thesis": "Private-sector bank in a valuation re-rating phase, supported by improving asset quality and retail-loan growth."},
    "BSE.NS":        {"name": "BSE Ltd", "class": "Equity", "sector": "Capital Markets",
                       "thesis": "India's oldest stock exchange; a high-beta play on retail derivatives-trading volumes and market-infrastructure growth."},
    "HINDUNILVR.NS": {"name": "Hindustan Unilever Ltd", "class": "Equity", "sector": "FMCG",
                       "thesis": "India's largest FMCG company; a low-beta defensive anchor with pricing power across home & personal-care categories."},
    "BRITANNIA.NS":  {"name": "Britannia Industries Ltd", "class": "Equity", "sector": "FMCG",
                       "thesis": "Dominant biscuits & bakery player expanding into adjacent categories; defensive earnings visibility."},
    "ITC.NS":        {"name": "ITC Ltd", "class": "Equity", "sector": "FMCG",
                       "thesis": "Diversified FMCG-cigarettes-agri-paper conglomerate; a defensive anchor with one of the highest dividend yields in the index."},
    "PIDILITIND.NS": {"name": "Pidilite Industries Ltd", "class": "Equity", "sector": "Chemicals",
                       "thesis": "Dominant adhesives (Fevicol) franchise with pricing power over raw-material cycles; a steady structural compounder."},
    "SOLARINDS.NS":  {"name": "Solar Industries India Ltd", "class": "Equity", "sector": "Chemicals / Defense",
                       "thesis": "Leading industrial-explosives maker with a fast-scaling defense ordnance order book; a high-beta aggressive-growth name."},
}

EQUITY_TICKERS = [t for t, m in ASSET_META.items() if m["class"] == "Equity"]
BOND_TICKERS   = ["10Y_GSEC", "AAA_BOND"]
ALL_TICKERS    = list(ASSET_META.keys())
YF_TICKERS     = [t for t in ALL_TICKERS if t not in BOND_TICKERS]

INDUSTRY_AVG_PE = {
    "Automobiles": 28.0, "Defense / Capital Goods": 40.0, "Capital Goods": 45.0,
    "Capital Goods / Manufacturing": 42.0, "Financials": 20.0, "Capital Markets": 35.0,
    "FMCG": 55.0, "Chemicals": 50.0, "Chemicals / Defense": 50.0,
}

# -----------------------------------------------------------------------------
# 3. SCENARIO TARGET WEIGHTS (must each sum to 100)
# -----------------------------------------------------------------------------
SCENARIOS = {
    "Conservative (₹1.75 Cr)": {
        "target": 1_75_00_000,
        "weights": {"10Y_GSEC": 10, "AAA_BOND": 7, "GOLDBEES.NS": 8,
                    "MARUTI.NS": 7, "BAJAJ-AUTO.NS": 6, "HAL.NS": 9, "SIEMENS.NS": 8,
                    "POLYCAB.NS": 11, "AXISBANK.NS": 5, "BSE.NS": 6, "HINDUNILVR.NS": 7,
                    "BRITANNIA.NS": 4, "ITC.NS": 4, "PIDILITIND.NS": 3, "SOLARINDS.NS": 5},
    },
    "Moderate (₹2.00 Cr)": {
        "target": 2_00_00_000,
        "weights": {"10Y_GSEC": 5, "AAA_BOND": 4, "GOLDBEES.NS": 6,
                    "MARUTI.NS": 4, "BAJAJ-AUTO.NS": 4, "HAL.NS": 15, "SIEMENS.NS": 9,
                    "POLYCAB.NS": 11, "AXISBANK.NS": 6, "BSE.NS": 13, "HINDUNILVR.NS": 4,
                    "BRITANNIA.NS": 3, "ITC.NS": 3, "PIDILITIND.NS": 3, "SOLARINDS.NS": 10},
    },
    "Aggressive (₹2.25 Cr)": {
        "target": 2_25_00_000,
        "weights": {"10Y_GSEC": 2, "AAA_BOND": 2, "GOLDBEES.NS": 3,
                    "MARUTI.NS": 2, "BAJAJ-AUTO.NS": 2, "HAL.NS": 24, "SIEMENS.NS": 6,
                    "POLYCAB.NS": 6, "AXISBANK.NS": 6, "BSE.NS": 20, "HINDUNILVR.NS": 3,
                    "BRITANNIA.NS": 2, "ITC.NS": 3, "PIDILITIND.NS": 3, "SOLARINDS.NS": 16},
    },
}

for _name, _sc in SCENARIOS.items():
    _tot = sum(_sc["weights"].values())
    assert abs(_tot - 100) < 1e-6, f"{_name} weights sum to {_tot}, expected 100"

# -----------------------------------------------------------------------------
# 4. OFFLINE FALLBACK FUNDAMENTALS (used if Yahoo Finance rate-limits / drops)
# -----------------------------------------------------------------------------
FALLBACK_DATA = {
    "MARUTI.NS":     {"cmp": 12800.0, "eps": 440.0, "pe": 29.0, "beta": 0.85, "mcap_cr": 402000, "low52": 10500.0, "high52": 13700.0, "buy_price": 9200.0},
    "BAJAJ-AUTO.NS": {"cmp": 9500.0,  "eps": 250.0, "pe": 38.0, "beta": 0.75, "mcap_cr": 265000, "low52": 7000.0,  "high52": 12800.0, "buy_price": 4300.0},
    "HAL.NS":        {"cmp": 4800.0,  "eps": 105.0, "pe": 45.7, "beta": 1.20, "mcap_cr": 320000, "low52": 3200.0,  "high52": 5675.0,  "buy_price": 1450.0},
    "SIEMENS.NS":    {"cmp": 6500.0,  "eps": 95.0,  "pe": 68.0, "beta": 1.05, "mcap_cr": 231000, "low52": 5200.0,  "high52": 8400.0,  "buy_price": 2600.0},
    "POLYCAB.NS":    {"cmp": 6900.0,  "eps": 150.0, "pe": 46.0, "beta": 0.95, "mcap_cr": 104000, "low52": 4800.0,  "high52": 7600.0,  "buy_price": 2200.0},
    "AXISBANK.NS":   {"cmp": 1180.0,  "eps": 78.0,  "pe": 15.1, "beta": 1.30, "mcap_cr": 365000, "low52": 950.0,   "high52": 1340.0,  "buy_price": 700.0},
    "BSE.NS":        {"cmp": 5200.0,  "eps": 95.0,  "pe": 54.7, "beta": 1.60, "mcap_cr": 70000,  "low52": 1800.0,  "high52": 6100.0,  "buy_price": 350.0},
    "HINDUNILVR.NS": {"cmp": 2500.0,  "eps": 43.0,  "pe": 58.1, "beta": 0.55, "mcap_cr": 588000, "low52": 2100.0,  "high52": 3035.0,  "buy_price": 2300.0},
    "BRITANNIA.NS":  {"cmp": 5700.0,  "eps": 90.0,  "pe": 63.3, "beta": 0.60, "mcap_cr": 137000, "low52": 4500.0,  "high52": 6470.0,  "buy_price": 3400.0},
    "ITC.NS":        {"cmp": 460.0,   "eps": 16.0,  "pe": 28.8, "beta": 0.65, "mcap_cr": 575000, "low52": 390.0,   "high52": 500.0,   "buy_price": 210.0},
    "PIDILITIND.NS": {"cmp": 3100.0,  "eps": 45.0,  "pe": 68.9, "beta": 0.70, "mcap_cr": 157000, "low52": 2500.0,  "high52": 3400.0,  "buy_price": 1750.0},
    "SOLARINDS.NS":  {"cmp": 12500.0, "eps": 180.0, "pe": 69.4, "beta": 1.55, "mcap_cr": 116000, "low52": 5900.0,  "high52": 13100.0, "buy_price": 1500.0},
    "GOLDBEES.NS":   {"cmp": 72.0,    "eps": None,  "pe": None, "beta": 0.10, "mcap_cr": None,   "low52": 50.0,    "high52": 78.0,    "buy_price": 45.0},
}

# -----------------------------------------------------------------------------
# 5. LIVE DATA FETCH WITH RESILIENT FALLBACK (never crashes)
# -----------------------------------------------------------------------------
RAW_CACHE = {}   # ticker -> {"hist": DataFrame|None, "info": dict, "live": bool}
NIFTY_HIST = None


def _safe_history(ticker, period="5y"):
    try:
        df = yf.Ticker(ticker).history(period=period, auto_adjust=True)
        return df if df is not None and not df.empty else None
    except Exception:
        return None


def _safe_info(ticker):
    try:
        info = yf.Ticker(ticker).info
        return info if isinstance(info, dict) else {}
    except Exception:
        return {}


def fetch_all_data():
    global NIFTY_HIST
    print("Fetching live NSE market data via yfinance (fallback engages automatically on failure)...")
    for t in YF_TICKERS:
        hist = _safe_history(t)
        info = _safe_info(t) if hist is not None else {}
        live = hist is not None and len(hist) > 5
        RAW_CACHE[t] = {"hist": hist, "info": info, "live": live}
        print(f"  {t:<16s} {'✓ live' if live else '⚠ offline fallback'}")
    NIFTY_HIST = _safe_history(BENCHMARK)
    print(f"  {'^NSEI (benchmark)':<16s} {'✓ live' if NIFTY_HIST is not None else '⚠ unavailable'}")
    print("Data fetch complete.\n")


fetch_all_data()

# -----------------------------------------------------------------------------
# 6. PRICE / BETA / ENTRY-DATE HELPERS
# -----------------------------------------------------------------------------
def get_entry_date(hist):
    """Trading date closest to (today - HOLDING_YEARS) present in the history index."""
    if hist is None or hist.empty:
        return None
    target = pd.Timestamp(datetime.now() - timedelta(days=365 * HOLDING_YEARS))
    idx = hist.index
    if idx.tz is not None and target.tzinfo is None:
        target = target.tz_localize(idx.tz)
    pos = idx.get_indexer([target], method="nearest")[0]
    return idx[pos]


def compute_beta_vs_nifty(hist):
    try:
        if NIFTY_HIST is None or NIFTY_HIST.empty or hist is None:
            return None
        s_ret = hist["Close"].pct_change().dropna()
        n_ret = NIFTY_HIST["Close"].pct_change().dropna()
        joined = pd.concat([s_ret, n_ret], axis=1, join="inner")
        joined.columns = ["s", "n"]
        if len(joined) < 30:
            return None
        var = joined["n"].var()
        return float(joined["s"].cov(joined["n"]) / var) if var > 0 else None
    except Exception:
        return None


def get_price_series(t):
    """Return buy_price / CMP / beta / 52w range / live-flag for an equity or gold ticker."""
    cache = RAW_CACHE.get(t, {})
    hist, info = cache.get("hist"), cache.get("info", {}) or {}
    fb = FALLBACK_DATA.get(t, {})
    live = cache.get("live", False)

    if live:
        cmp_ = float(hist["Close"].iloc[-1])
        entry_date = get_entry_date(hist)
        buy_price = float(hist.loc[entry_date, "Close"]) if entry_date is not None else float(hist["Close"].iloc[0])
        beta = info.get("beta") or compute_beta_vs_nifty(hist) or fb.get("beta", 1.0)
        low52 = float(hist["Close"].tail(252).min())
        high52 = float(hist["Close"].tail(252).max())
    else:
        cmp_ = fb.get("cmp", 100.0)
        buy_price = fb.get("buy_price", cmp_ * 0.6)
        beta = fb.get("beta", 1.0)
        low52 = fb.get("low52", cmp_ * 0.8)
        high52 = fb.get("high52", cmp_ * 1.2)

    return {"cmp": cmp_, "buy_price": buy_price, "beta": beta,
            "low52": low52, "high52": high52, "live": live, "info": info}


# -----------------------------------------------------------------------------
# 7. SCENARIO PORTFOLIO ENGINE (allocation → P&L → risk metrics)
# -----------------------------------------------------------------------------
def compute_scenario(scenario_name):
    sc = SCENARIOS[scenario_name]
    rows = []

    for t, w_pct in sc["weights"].items():
        meta = ASSET_META[t]
        allocated = TOTAL_CAPITAL * w_pct / 100.0

        if meta["class"] == "Debt":
            invested = allocated
            current_value = invested * ((1 + meta["yield"]) ** HOLDING_YEARS)
            qty = buy_price = cmp_ = None
            beta = 0.0
        else:
            p = get_price_series(t)
            buy_price, cmp_, beta = p["buy_price"], p["cmp"], p["beta"]
            qty = int(allocated / buy_price) if buy_price and buy_price > 0 else 0
            invested = qty * buy_price
            current_value = qty * cmp_
            leftover = allocated - invested          # uninvested residual cash (odd-lot rounding)
            invested += leftover
            current_value += leftover

        gross_profit = current_value - invested
        brokerage = BROKERAGE_RATE * (invested + current_value)
        taxable_gain = max(gross_profit - brokerage, 0)
        stcg = STCG_RATE * taxable_gain
        net_profit = gross_profit - brokerage - stcg
        cagr = (current_value / invested) ** (1 / HOLDING_YEARS) - 1 if invested > 0 else 0.0

        rows.append({
            "ticker": t, "name": meta["name"], "class": meta["class"], "sector": meta.get("sector", ""),
            "weight_pct": w_pct, "allocated": allocated, "qty": qty, "buy_price": buy_price, "cmp": cmp_,
            "invested": invested, "current_value": current_value, "gross_profit": gross_profit,
            "brokerage": brokerage, "stcg": stcg, "net_profit": net_profit, "beta": beta, "cagr": cagr,
        })

    df = pd.DataFrame(rows)
    inv_sum, cur_sum = df["invested"].sum(), df["current_value"].sum()
    kpis = {
        "current_value": cur_sum, "invested": inv_sum,
        "gross_profit": df["gross_profit"].sum(), "brokerage": df["brokerage"].sum(),
        "stcg": df["stcg"].sum(), "net_profit": df["net_profit"].sum(),
        "net_return_pct": (cur_sum / inv_sum - 1) * 100 if inv_sum else 0.0,
        "weighted_beta": (df["weight_pct"] / 100 * df["beta"]).sum(),
        "target": sc["target"],
    }
    return df, kpis


# -----------------------------------------------------------------------------
# 8. 5-YEAR NORMALIZED PORTFOLIO-VS-NIFTY INDEX SERIES
# -----------------------------------------------------------------------------
def get_nifty_norm():
    if NIFTY_HIST is None or NIFTY_HIST.empty:
        return None
    close = NIFTY_HIST["Close"]
    return close / close.iloc[0] * 100


def build_portfolio_index_series(scenario_name):
    """Relative (base=100) 5Y value path for one scenario, aligned to the Nifty calendar."""
    if NIFTY_HIST is None or NIFTY_HIST.empty:
        return None

    weights = SCENARIOS[scenario_name]["weights"]
    master_idx = NIFTY_HIST.index
    days = (master_idx - master_idx[0]).days.values

    portfolio_rel = pd.Series(0.0, index=master_idx)
    for t, w_pct in weights.items():
        meta = ASSET_META[t]
        w = w_pct / 100.0
        if meta["class"] == "Debt":
            rel = pd.Series((1 + meta["yield"]) ** (days / 365.0), index=master_idx)
        else:
            hist = RAW_CACHE.get(t, {}).get("hist")
            if hist is not None and not hist.empty:
                s = hist["Close"].reindex(master_idx, method="ffill").bfill()
                rel = s / s.iloc[0]
            else:
                fb_cagr = 0.15  # conservative fallback growth path when no history is available
                rel = pd.Series((1 + fb_cagr) ** (days / 365.0), index=master_idx)
        portfolio_rel = portfolio_rel.add(rel * w, fill_value=0)

    return portfolio_rel * 100


# -----------------------------------------------------------------------------
# 9. PRECOMPUTE EVERYTHING ONCE — scenario switching is then pure UI, zero recompute
# -----------------------------------------------------------------------------
NIFTY_NORM = get_nifty_norm()

SCENARIO_CACHE = {}
for _name in SCENARIOS:
    _df, _kpis = compute_scenario(_name)
    SCENARIO_CACHE[_name] = {
        "df": _df,
        "kpis": _kpis,
        "port_idx": build_portfolio_index_series(_name),
    }

CLASS_ORDER = ["Equity", "Debt", "Gold"]
CLASS_COLORS = ["#1a73e8", "#5f6368", "#fbbc04"]

# One-time global CSS (cards + table). Injected once; widgets only update .value afterwards,
# never re-inject markup, so there is no flicker / duplicate-style buildup on repeat clicks.
GLOBAL_CSS = """
<style>
.pf-card{flex:1 1 190px;background:#fff;border-radius:10px;padding:14px 18px;
         box-shadow:0 1px 4px rgba(0,0,0,0.15);}
.pf-card .lbl{font-size:11px;color:#5f6368;text-transform:uppercase;letter-spacing:.5px;font-family:Arial,Helvetica,sans-serif;}
.pf-card .val{font-size:20px;font-weight:700;margin-top:4px;font-family:Arial,Helvetica,sans-serif;}
.pf-gap{font-family:Arial,Helvetica,sans-serif;font-size:13px;margin:2px 0 18px 0;}
.holdings-table{border-collapse:collapse;width:100%;font-family:Arial,Helvetica,sans-serif;font-size:13px;}
.holdings-table th{background:#202124;color:#fff;padding:9px 10px;text-align:right;position:sticky;top:0;}
.holdings-table th:first-child,.holdings-table th:nth-child(2){text-align:left;}
.holdings-table td{padding:8px 10px;text-align:right;border-bottom:1px solid #e8eaed;white-space:nowrap;}
.holdings-table td:first-child,.holdings-table td:nth-child(2){text-align:left;}
.holdings-table tr:nth-child(even){background:#f8f9fa;}
.holdings-table tr:hover{background:#e8f0fe;}
.scenario-caption{font-family:Arial,Helvetica,sans-serif;color:#5f6368;font-size:13px;margin:4px 0 14px 0;}
</style>
"""

# -----------------------------------------------------------------------------
# 10. UI BUILDING BLOCKS — persistent widgets, updated via .value / batch_update
#     (this is what removes the lag and the "sometimes doesn't render" flakiness:
#      a fresh go.Figure()+display() on every click was being re-drawn from
#      scratch each time and occasionally raced with Output.clear_output();
#      a FigureWidget is created ONCE and only patches its own data afterwards.)
# -----------------------------------------------------------------------------
kpi_html = widgets.HTML()
table_html = widgets.HTML()
caption_html = widgets.HTML()

def render_kpi_cards_html(kpis):
    cards = [
        ("Current Portfolio Value", inr(kpis["current_value"]), "#1a73e8"),
        ("Total Invested", inr(kpis["invested"]), "#5f6368"),
        ("Gross Profit", inr(kpis["gross_profit"]), "#188038" if kpis["gross_profit"] >= 0 else "#d93025"),
        ("Total Brokerage", inr(kpis["brokerage"]), "#e37400"),
        ("Estimated STCG Tax (20%)", inr(kpis["stcg"]), "#e37400"),
        ("Net Take-Home Profit", inr(kpis["net_profit"]), "#188038" if kpis["net_profit"] >= 0 else "#d93025"),
        ("Net Portfolio Return", f"{kpis['net_return_pct']:.2f}%", "#188038" if kpis["net_return_pct"] >= 0 else "#d93025"),
        ("Weighted Portfolio Beta", f"{kpis['weighted_beta']:.2f}", "#6a0dad"),
    ]
    html = "<div style='display:flex;flex-wrap:wrap;gap:14px;'>"
    for label, value, color in cards:
        html += (f"<div class='pf-card' style='border-top:4px solid {color};'>"
                 f"<div class='lbl'>{label}</div><div class='val' style='color:{color};'>{value}</div></div>")
    html += "</div>"
    gap = kpis["target"] - kpis["current_value"]
    gap_color = "#188038" if gap <= 0 else "#d93025"
    gap_text = "Target achieved / exceeded ✅" if gap <= 0 else f"Shortfall to target: {inr(gap)}"
    html += (f"<div class='pf-gap' style='color:{gap_color};'>"
             f"3-Year Target: {inr(kpis['target'])} &nbsp;|&nbsp; {gap_text}</div>")
    return html


def render_table_html(df):
    show = df.copy()
    show["Weight %"] = show["weight_pct"].map(lambda v: f"{v:.1f}%")
    show["Allocated"] = show["allocated"].map(inr)
    show["Qty"] = show["qty"].map(lambda v: "-" if v is None or pd.isna(v) else f"{int(v):,}")
    show["Buy Price"] = show["buy_price"].map(lambda v: "-" if v is None or pd.isna(v) else inr(v))
    show["CMP"] = show["cmp"].map(lambda v: "-" if v is None or pd.isna(v) else inr(v))
    show["Current Value"] = show["current_value"].map(inr)
    show["Net Profit"] = show["net_profit"].map(inr)
    show["CAGR"] = show["cagr"].map(lambda v: f"{v * 100:.2f}%")
    show["Beta"] = show["beta"].map(lambda v: f"{v:.2f}")
    cols = ["name", "class", "Weight %", "Allocated", "Qty", "Buy Price", "CMP",
            "Current Value", "Net Profit", "CAGR", "Beta"]
    show = show[cols].rename(columns={"name": "Asset", "class": "Class"})
    return show.to_html(index=False, escape=False, classes="holdings-table", border=0)


# ---- FigureWidgets (built once with the default scenario's data) ----------
_default = list(SCENARIOS.keys())[0]
_d0 = SCENARIO_CACHE[_default]

def _class_values(df):
    grp = df.groupby("class")["current_value"].sum().reindex(CLASS_ORDER).fillna(0)
    return grp.index.tolist(), grp.values.tolist()

_labels0, _values0 = _class_values(_d0["df"])
donut_widget = go.FigureWidget(
    data=[go.Pie(labels=_labels0, values=_values0, hole=0.55, marker=dict(colors=CLASS_COLORS))],
    layout=go.Layout(title=f"Asset Class Allocation — {_default}", height=380, width=420,
                      template="plotly_white", legend=dict(orientation="h", y=-0.1),
                      margin=dict(t=60, b=40))
)

_d0_sorted = _d0["df"].sort_values("net_profit")
bar_widget = go.FigureWidget(
    data=[go.Bar(
        x=_d0_sorted["net_profit"], y=_d0_sorted["name"], orientation="h",
        marker_color=["#188038" if v >= 0 else "#d93025" for v in _d0_sorted["net_profit"]],
        text=[inr(v) for v in _d0_sorted["net_profit"]], textposition="outside",
    )],
    layout=go.Layout(title=f"Asset-wise Net Profit / Loss — {_default}", height=520, width=640,
                      template="plotly_white", margin=dict(l=190, t=60))
)

line_widget = go.FigureWidget(
    data=[
        go.Scatter(x=(_d0["port_idx"].index if _d0["port_idx"] is not None else []),
                   y=(_d0["port_idx"].values if _d0["port_idx"] is not None else []),
                   mode="lines", name="Portfolio", line=dict(color="#1a73e8", width=2)),
        go.Scatter(x=(NIFTY_NORM.index if NIFTY_NORM is not None else []),
                   y=(NIFTY_NORM.values if NIFTY_NORM is not None else []),
                   mode="lines", name="Nifty 50", line=dict(color="#e37400", width=2, dash="dot")),
    ],
    layout=go.Layout(title=f"5-Year Normalized Return: Portfolio vs Nifty 50 (Base = ₹100) — {_default}",
                      height=400, template="plotly_white", xaxis_title="Date", yaxis_title="Indexed Value")
)
if NIFTY_NORM is None:
    line_widget.add_annotation(text="Benchmark history unavailable", showarrow=False)


def update_dashboard(scenario_name):
    data = SCENARIO_CACHE[scenario_name]
    df, kpis, port_idx = data["df"], data["kpis"], data["port_idx"]

    kpi_html.value = render_kpi_cards_html(kpis)
    table_html.value = render_table_html(df)
    caption_html.value = f"<div class='scenario-caption'>Showing: <b>{scenario_name}</b></div>"

    labels, values = _class_values(df)
    with donut_widget.batch_update():
        donut_widget.data[0].labels = labels
        donut_widget.data[0].values = values
        donut_widget.layout.title.text = f"Asset Class Allocation — {scenario_name}"

    d = df.sort_values("net_profit")
    with bar_widget.batch_update():
        bar_widget.data[0].x = d["net_profit"].values
        bar_widget.data[0].y = d["name"].values
        bar_widget.data[0].marker.color = ["#188038" if v >= 0 else "#d93025" for v in d["net_profit"]]
        bar_widget.data[0].text = [inr(v) for v in d["net_profit"]]
        bar_widget.layout.title.text = f"Asset-wise Net Profit / Loss — {scenario_name}"

    with line_widget.batch_update():
        if port_idx is not None:
            line_widget.data[0].x = port_idx.index
            line_widget.data[0].y = port_idx.values
        line_widget.layout.title.text = f"5-Year Normalized Return: Portfolio vs Nifty 50 (Base = ₹100) — {scenario_name}"


# -----------------------------------------------------------------------------
# 11. SCENARIO BUTTONS (replaces the dropdown)
# -----------------------------------------------------------------------------
SCENARIO_STYLE = {  # a fixed accent colour per risk profile, independent of selection state
    list(SCENARIOS.keys())[0]: "info",
    list(SCENARIOS.keys())[1]: "warning",
    list(SCENARIOS.keys())[2]: "danger",
}
CURRENT_SCENARIO = {"name": _default}
scenario_buttons = {}

for _name in SCENARIOS:
    _btn = widgets.Button(
        description=_name, layout=widgets.Layout(width="240px", height="46px"),
        style=widgets.ButtonStyle(font_weight="bold"),
    )
    scenario_buttons[_name] = _btn

def _restyle_buttons():
    for _name, _btn in scenario_buttons.items():
        if _name == CURRENT_SCENARIO["name"]:
            _btn.button_style = SCENARIO_STYLE[_name]
            _btn.icon = "check"
        else:
            _btn.button_style = ""
            _btn.icon = ""

def _make_click_handler(name):
    def _handler(_):
        if CURRENT_SCENARIO["name"] == name:
            return
        CURRENT_SCENARIO["name"] = name
        _restyle_buttons()
        update_dashboard(name)
    return _handler

for _name, _btn in scenario_buttons.items():
    _btn.on_click(_make_click_handler(_name))

_restyle_buttons()
button_row = widgets.HBox(list(scenario_buttons.values()),
                           layout=widgets.Layout(gap="10px", margin="4px 0 14px 0"))

# -----------------------------------------------------------------------------
# 12. UI — COMPANY DEEP-DIVE SCREENER (dropdown retained: 12 names don't fit as buttons)
# -----------------------------------------------------------------------------
company_dropdown = widgets.Dropdown(
    options=[(ASSET_META[t]["name"], t) for t in EQUITY_TICKERS],
    description="Select Company:", style={"description_width": "initial"},
    layout=widgets.Layout(width="420px"),
)
company_card_html = widgets.HTML()

def valuation_status(pe, sector):
    avg = INDUSTRY_AVG_PE.get(sector)
    if pe is None or avg is None:
        return "N/A"
    diff = (pe - avg) / avg
    if diff > 0.15:
        return f"Overvalued vs {sector} avg ({avg:.1f}x)"
    if diff < -0.15:
        return f"Undervalued vs {sector} avg ({avg:.1f}x)"
    return f"Fairly valued vs {sector} avg ({avg:.1f}x)"


def _company_snapshot(ticker):
    meta = ASSET_META[ticker]
    p = get_price_series(ticker)
    info, fb = p["info"], FALLBACK_DATA.get(ticker, {})
    cmp_, hist = p["cmp"], RAW_CACHE.get(ticker, {}).get("hist")
    pe = info.get("trailingPE") or fb.get("pe")
    eps = info.get("trailingEps") or fb.get("eps")
    mcap = info.get("marketCap")
    mcap_cr = (mcap / 1e7) if mcap else fb.get("mcap_cr")
    beta = p["beta"]
    low52 = info.get("fiftyTwoWeekLow") or p["low52"]
    high52 = info.get("fiftyTwoWeekHigh") or p["high52"]
    if hist is not None and not hist.empty and len(hist) > 1:
        day_change_pct = (cmp_ - float(hist["Close"].iloc[-2])) / float(hist["Close"].iloc[-2]) * 100
    else:
        day_change_pct = 0.0
    return dict(meta=meta, cmp=cmp_, hist=hist, pe=pe, eps=eps, mcap_cr=mcap_cr,
                beta=beta, low52=low52, high52=high52, day_change_pct=day_change_pct, live=p["live"])


_c0 = _company_snapshot(EQUITY_TICKERS[0])
_h0 = _c0["hist"]
dma_widget = go.FigureWidget(
    data=[
        go.Scatter(x=(_h0.index if _h0 is not None else []), y=(_h0["Close"] if _h0 is not None else []),
                   name="Close", line=dict(color="#1a73e8")),
        go.Scatter(x=(_h0.index if _h0 is not None else []),
                   y=(_h0["Close"].rolling(50).mean() if _h0 is not None else []),
                   name="50 DMA", line=dict(color="#e37400", width=1.3)),
        go.Scatter(x=(_h0.index if _h0 is not None else []),
                   y=(_h0["Close"].rolling(200).mean() if _h0 is not None else []),
                   name="200 DMA", line=dict(color="#d93025", width=1.3)),
    ],
    layout=go.Layout(title=f"{_c0['meta']['name']} — 5-Year Price with 50/200 DMA",
                      template="plotly_white", height=430, xaxis=dict(rangeslider=dict(visible=True)))
)
if _h0 is None:
    dma_widget.add_annotation(text="5-year chart unavailable — offline fallback mode", showarrow=False)


def update_company(ticker):
    snap = _company_snapshot(ticker)
    meta, hist = snap["meta"], snap["hist"]
    change_color = "#188038" if snap["day_change_pct"] >= 0 else "#d93025"
    mcap_txt = ("₹" + format(snap["mcap_cr"], ",.0f") + " Cr") if snap["mcap_cr"] else "N/A"
    pe_txt = f"{snap['pe']:.1f}x" if snap["pe"] else "N/A"
    eps_txt = f"₹{snap['eps']:.2f}" if snap["eps"] else "N/A"
    val_status = valuation_status(snap["pe"], meta["sector"])

    company_card_html.value = f"""
    <div style='font-family:Arial;background:#fff;border-radius:10px;padding:18px;
                box-shadow:0 1px 4px rgba(0,0,0,0.15);margin-bottom:14px;'>
      <h3 style='margin:0 0 4px 0;'>{meta['name']} <span style='color:#5f6368;font-size:14px;'>({ticker})</span></h3>
      <div style='color:#5f6368;font-size:13px;margin-bottom:10px;'>
          {meta['sector']} — {"Live Data" if snap['live'] else "⚠ Offline Fallback Data"}
      </div>
      <div style='display:flex;flex-wrap:wrap;gap:22px;font-size:14px;'>
        <div><b>CMP:</b> {inr(snap['cmp'])}</div>
        <div style='color:{change_color};'><b>Day Change:</b> {snap['day_change_pct']:+.2f}%</div>
        <div><b>Market Cap:</b> {mcap_txt}</div>
        <div><b>Trailing P/E:</b> {pe_txt}</div>
        <div><b>Trailing EPS:</b> {eps_txt}</div>
        <div><b>Beta:</b> {snap['beta']:.2f}</div>
        <div><b>52W Range:</b> {inr(snap['low52'])} – {inr(snap['high52'])}</div>
      </div>
      <div style='margin-top:10px;font-size:13px;'><b>Valuation Status:</b> {val_status}</div>
      <p style='margin-top:12px;font-size:13px;color:#3c4043;line-height:1.5;'>{meta['thesis']}</p>
    </div>"""

    with dma_widget.batch_update():
        if hist is not None and not hist.empty:
            dma_widget.data[0].x = hist.index
            dma_widget.data[0].y = hist["Close"]
            dma_widget.data[1].x = hist.index
            dma_widget.data[1].y = hist["Close"].rolling(50).mean()
            dma_widget.data[2].x = hist.index
            dma_widget.data[2].y = hist["Close"].rolling(200).mean()
        dma_widget.layout.title.text = f"{meta['name']} — 5-Year Price with 50/200 DMA"


def _on_company_change(change):
    if change["name"] == "value":
        update_company(change["new"])

company_dropdown.observe(_on_company_change, names="value")

# -----------------------------------------------------------------------------
# 13. ASSEMBLE & RENDER
# -----------------------------------------------------------------------------
display(HTML(GLOBAL_CSS))
display(HTML("<h1 style='font-family:Arial;'>🇮🇳 3-Year Indian Equity Portfolio Dashboard</h1>"
             "<p style='font-family:Arial;color:#5f6368;'>₹1 Crore capital · 15-asset universe · "
             "click a risk profile below to switch scenarios instantly</p>"))
display(button_row)
display(caption_html)
display(kpi_html)
display(widgets.HBox([donut_widget, bar_widget]))
display(line_widget)
display(HTML("<h3 style='font-family:Arial;'>Holdings Detail</h3>"))
display(table_html)

update_dashboard(_default)   # populate everything for the default scenario on first load

display(HTML("<hr><h2 style='font-family:Arial;'>🔎 Company Deep-Dive Screener</h2>"))
display(company_dropdown)
display(company_card_html)
display(dma_widget)

update_company(EQUITY_TICKERS[0])